### ISSUE TITLE
Readme needs basic usage

### ISSUE THREAD

**Issue by webframp** [hw-labs/sparkle-pack-aws-amis#1]
To help the copy-pasters

**Comment by luckymike** [comment]
:+1: I'm planning on it soon! If you need an immediate reference, this pack is used here: 
https://github.com/sensu/sensu-eval-stack/blob/master/sparkleformation/sensu_stack.rb#L3

**Comment by luckymike** [comment]
How's #2 look? (other than being a very strange Master -> Develop PR)

**Comment by luckymike** [comment]
Thanks for prodding me. Closing and merging the docs!
